<a href="https://colab.research.google.com/github/JadoHR/Personal_Projects_Jean_De_Dieu/blob/main/Case_study_type_1_Jado_%26_Mahdy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***This project focuses on data preprocessing and cleaning using Python. The dataset is analyzed to detect missing values, noisy data (illogical ages), inconsistent text entries, and duplicate records. Data cleaning techniques such as median/mode imputation, text normalization, duplicate removal, and categorical encoding using LabelEncoder are applied to prepare the dataset for machine learning or data analysis.***

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Load dataset
dataset = pd.read_csv('[IP] DATASET SC PRE-PROCESSING TYPE 1.csv')
dataset

     user_id  gender   age country subscription_type  listening_time
0          1  Female  54.0      CA              Free            26.0
1          2   Other  33.0      DE            Family           141.0
2          3    Male  38.0      AU           Premium           199.0
3          4  Female  22.0      CA           Student            36.0
4          5   Other  29.0      US            Family           250.0
..       ...     ...   ...     ...               ...             ...
496      496   Other  17.0      PK           Premium           141.0
497      497  Female  37.0      IN            Family           184.0
498      498    Male  55.0      CA           Student           118.0
499      499  Female  48.0      FR           Premium           164.0
500      500   Other  38.0      IN              Free           283.0

[501 rows x 6 columns]

In [ ]:
# Display dataset info
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            501 non-null    int64
 1   gender             501 non-null    object
 2   age                500 non-null    float64
 3   country            501 non-null    object
 4   subscription_type  500 non-null    object
 5   listening_time     500 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 23.6+ KB

In [ ]:
# --- STEP B: IDENTIFY MISSING DATA ---
missing_data = dataset[dataset.isnull().any(axis=1)]   # axis=1 → row-wise check
missing_data

     user_id  gender   age country subscription_type  listening_time
184      184  Female   NaN      DE           Premium           140.0
418      418    Male  42.0      UK               NaN            23.0
489      489    Male  43.0      AU           Premium             NaN

In [ ]:
# Drop missing data (alternative cleaning version)
dataclean1 = dataset.dropna()
dataclean1

     user_id  gender   age country subscription_type  listening_time
0          1  Female  54.0      CA              Free            26.0
1          2   Other  33.0      DE            Family           141.0
2          3    Male  38.0      AU           Premium           199.0
3          4  Female  22.0      CA           Student            36.0
4          5   Other  29.0      US            Family           250.0
..       ...     ...   ...     ...               ...             ...
496      496   Other  17.0      PK           Premium           141.0
497      497  Female  37.0      IN            Family           184.0
498      498    Male  55.0      CA           Student           118.0
499      499  Female  48.0      FR           Premium           164.0
500      500   Other  38.0      IN              Free           283.0

[498 rows x 6 columns]

In [ ]:
# --- STEP C: CHECK NOISE (ILLOGICAL OR WRONG AGE VALUES) ---
# Example: Find users with illogical ages (below 10 or above 100)
noise_data = dataclean1[(dataclean1['age'] < 10) | (dataclean1['age'] > 100)]
noise_data

     user_id gender    age country subscription_type  listening_time
21        22   Male  200.0      AU           Premium            20.0
106      106  Other  234.0      AU           Student           251.0

In [ ]:
# Replace illogical ages with median
median_age = dataclean1['age'].median()
dataclean1.loc[dataclean1['age'] < 10, 'age'] = median_age
dataclean1.loc[dataclean1['age'] > 100, 'age'] = median_age
dataclean1

     user_id  gender   age country subscription_type  listening_time
0          1  Female  54.0      CA              Free            26.0
1          2   Other  33.0      DE            Family           141.0
2          3    Male  38.0      AU           Premium           199.0
3          4  Female  22.0      CA           Student            36.0
4          5   Other  29.0      US            Family           250.0
..       ...     ...   ...     ...               ...             ...
496      496   Other  17.0      PK           Premium           141.0
497      497  Female  37.0      IN            Family           184.0
498      498    Male  55.0      CA           Student           118.0
499      499  Female  48.0      FR           Premium           164.0
500      500   Other  38.0      IN              Free           283.0

[498 rows x 6 columns]

In [ ]:
# --- STEP D: INCONSISTENT DATA (Subscription Type Text Variation) ---
# Check inconsistent entries
inconsistent_data = dataclean1[~dataclean1['subscription_type'].isin(['Free','Premium','Student','Family'])]
inconsistent_data

    user_id  gender   age country subscription_type  listening_time
5         6  Female  17.0      AU             Free0           219.0
30       31   Other  44.0      UK          Premium#           149.0

In [ ]:
# Fix text inconsistency (capitalize first letter)
dataclean1['subscription_type'] = dataclean1['subscription_type'].astype(str).str.strip().str.title()
dataclean1

/tmp/ipython-input-1625422306.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataclean1['subscription_type'] = dataclean1['subscription_type'].astype(str).str.strip().str.title()

     user_id  gender   age country subscription_type  listening_time
0          1  Female  54.0      CA              Free            26.0
1          2   Other  33.0      DE            Family           141.0
2          3    Male  38.0      AU           Premium           199.0
3          4  Female  22.0      CA           Student            36.0
4          5   Other  29.0      US            Family           250.0
..       ...     ...   ...     ...               ...             ...
496      496   Other  17.0      PK           Premium           141.0
497      497  Female  37.0      IN            Family           184.0
498      498    Male  55.0      CA           Student           118.0
499      499  Female  48.0      FR           Premium           164.0
500      500   Other  38.0      IN              Free           283.0

[498 rows x 6 columns]

In [ ]:
# --- STEP E: DUPLICATE DATA ---
duplicate_data = dataclean1[dataclean1.duplicated(keep=False)]
duplicate_data

    user_id  gender   age country subscription_type  listening_time
20       21  Female  33.0      AU           Student           138.0
82       21  Female  33.0      AU           Student           138.0

In [ ]:
# Remove duplicate data
dataclean2 = dataclean1.drop_duplicates()
dataclean2

     user_id  gender   age country subscription_type  listening_time
0          1  Female  54.0      CA              Free            26.0
1          2   Other  33.0      DE            Family           141.0
2          3    Male  38.0      AU           Premium           199.0
3          4  Female  22.0      CA           Student            36.0
4          5   Other  29.0      US            Family           250.0
..       ...     ...   ...     ...               ...             ...
496      496   Other  17.0      PK           Premium           141.0
497      497  Female  37.0      IN            Family           184.0
498      498    Male  55.0      CA           Student           118.0
499      499  Female  48.0      FR           Premium           164.0
500      500   Other  38.0      IN              Free           283.0

[497 rows x 6 columns]

In [ ]:
# --- STEP F: TRANSFORM CATEGORICAL TO NUMERIC (ENCODING) ---
le = LabelEncoder()

In [ ]:
# Encode 'subscription_type'
dataclean2['subscription_type'] = le.fit_transform(dataclean2['subscription_type'])
dataclean2

/tmp/ipython-input-3210456423.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataclean2['subscription_type'] = le.fit_transform(dataclean2['subscription_type'])

     user_id  gender   age country  subscription_type  listening_time
0          1  Female  54.0      CA                  1            26.0
1          2   Other  33.0      DE                  0           141.0
2          3    Male  38.0      AU                  3           199.0
3          4  Female  22.0      CA                  5            36.0
4          5   Other  29.0      US                  0           250.0
..       ...     ...   ...     ...                ...             ...
496      496   Other  17.0      PK                  3           141.0
497      497  Female  37.0      IN                  0           184.0
498      498    Male  55.0      CA                  5           118.0
499      499  Female  48.0      FR                  3           164.0
500      500   Other  38.0      IN                  1           283.0

[497 rows x 6 columns]

In [ ]:
# Print label encoding mapping
for i, label in enumerate(le.classes_):
    print(f"{i}: {label}")

0: Family
1: Free
2: Free0
3: Premium
4: Premium#
5: Student

In [ ]:
# --- STEP G: FINAL CLEANED DATASET OUTPUT ---
dataclean2

     user_id  gender   age country  subscription_type  listening_time
0          1  Female  54.0      CA                  1            26.0
1          2   Other  33.0      DE                  0           141.0
2          3    Male  38.0      AU                  3           199.0
3          4  Female  22.0      CA                  5            36.0
4          5   Other  29.0      US                  0           250.0
..       ...     ...   ...     ...                ...             ...
496      496   Other  17.0      PK                  3           141.0
497      497  Female  37.0      IN                  0           184.0
498      498    Male  55.0      CA                  5           118.0
499      499  Female  48.0      FR                  3           164.0
500      500   Other  38.0      IN                  1           283.0

[497 rows x 6 columns]

In [ ]:
# Save cleaned data (optional)
dataclean2.to_csv('CLEANED_[IP]_DATASET.csv', index=False)

In [ ]:
# Save cleaned dataset in Colab environment
dataclean2.to_csv("CLEANED_[IP]_DATASET.csv", index=False)

# Download file to your computer
from google.colab import files
files.download("CLEANED_[IP]_DATASET.csv")

#2nd part

In [ ]:
# --- PART A: IDENTIFY DATA ISSUES ---

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Load dataset
dataset = pd.read_csv('[IP] DATASET SC PRE-PROCESSING TYPE 1.csv')
dataset

# Dataset info
dataset.info()

# Missing values
missing_data = dataset[dataset.isnull().any(axis=1)]
missing_data

# Drop missing data (optional clean version)
dataclean1 = dataset.dropna()
dataclean1

# Detect noisy (illogical) ages
noise_data = dataclean1[(dataclean1['age'] < 10) | (dataclean1['age'] > 100)]
noise_data

# Detect inconsistent subscription types
inconsistent_data = dataclean1[~dataclean1['subscription_type'].isin(['Free','Premium','Student','Family'])]
inconsistent_data

# Detect duplicates
duplicate_data = dataclean1[dataclean1.duplicated(keep=False)]
duplicate_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            501 non-null    int64
 1   gender             501 non-null    object
 2   age                500 non-null    float64
 3   country            501 non-null    object
 4   subscription_type  500 non-null    object
 5   listening_time     500 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 23.6+ KB

    user_id  gender   age country subscription_type  listening_time
20       21  Female  33.0      AU           Student           138.0
82       21  Female  33.0      AU           Student           138.0

In [ ]:
# --- PART B: DATA CLEANING & TRANSFORMATION ---

# Replace missing values with median/mode
dataset['age'].fillna(dataset['age'].median(), inplace=True)
dataset['gender'].fillna(dataset['gender'].mode()[0], inplace=True)
dataset['country'].fillna(dataset['country'].mode()[0], inplace=True)
dataset['subscription_type'].fillna('Free', inplace=True)
dataset['listening_time'].fillna(dataset['listening_time'].median(), inplace=True)

# Remove duplicates
dataset = dataset.drop_duplicates()

# Fix inconsistent text format
dataset['subscription_type'] = dataset['subscription_type'].astype(str).str.strip().str.title()

# Fix illogical ages
median_age = dataset['age'].median()
dataset.loc[(dataset['age'] < 10) | (dataset['age'] > 100), 'age'] = median_age

# Transform categorical data into numeric
le = LabelEncoder()
dataset['subscription_type'] = le.fit_transform(dataset['subscription_type'])

# Show cleaned dataset
dataset.head()

# Save cleaned file (optional)
dataset.to_csv('CLEANED_[IP]_DATASET.csv', index=False)
print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

/tmp/ipython-input-3658545241.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['age'].fillna(dataset['age'].median(), inplace=True)
/tmp/ipython-input-3658545241.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['gender'].fillna(dataset['gender'].mode()[0], inplace=True)
/tmp/ipython-input-3658545241.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['country'].fillna(dataset['country'].mode()[0], inplace=True)
/tmp/ipython-input-3658545241.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['subscription_type'].fillna('Free', inplace=True)
/tmp/ipython-input-3658545241.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['listening_time'].fillna(dataset['listening_time'].median(), inplace=True)

| Library                                  | Description                                                                                            |
| ---------------------------------------- | ------------------------------------------------------------------------------------------------------ |
| **pandas**                               | Used to read, clean, and manipulate tabular data (handle missing values, duplicates, inconsistencies). |
| **numpy**                                | Provides numerical functions and supports data replacement (e.g., median, mean).                       |
| **sklearn.preprocessing (LabelEncoder)** | Used to convert categorical text data (e.g., “Free”, “Premium”) into numeric values for analysis.      |

| Function                       | Description                                               |
| ------------------------------ | --------------------------------------------------------- |
| `pd.read_csv()`                | Loads dataset from CSV file.                              |
| `dataset.info()`               | Displays data structure, data types, and non-null values. |
| `dataset.isnull().any(axis=1)` | Finds rows with missing data.                             |
| `dataset.dropna()`             | Removes rows containing missing values.                   |
| `dataset.duplicated()`         | Detects duplicate records.                                |
| `dataset.drop_duplicates()`    | Removes duplicate rows.                                   |
| `LabelEncoder()`               | Converts categorical text to numeric labels.              |
| `dataset.fillna()`             | Fills missing data with median, mean, or mode.            |
| `dataset.to_csv()`             | Exports cleaned dataset to CSV file.                      |