<a href="https://colab.research.google.com/github/JadoHR/Personal_Projects_Jean_De_Dieu/blob/main/Data_mining_practcum_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**This case study demonstrates data preprocessing and cleaning on a movie dataset using Python. It identifies missing values, noisy budget data, inconsistent country names, and duplicate records, then applies cleaning techniques and LabelEncoder to transform categorical variables for data mining analysis.**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
dataset = pd.read_csv('DATA PREPROCESS.csv')
dataset

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,China22,6577427.79
1,2,He however experience,Comedy,1988.0,USA23,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,USA24,2468079.29
3,4,Exactly live,Comedy,1998.0,USA,1447311.46
4,5,Focus improve especially?,Documentary,2021.0,India,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,Documentary,1985.0,USA,5538344.45
1997,1998,Others line four,Action,2018.0,UK,6596913.87
1998,1999,Culture theory,Drama,1986.0,France,633992.99
1999,2000,Important almost,Action,1977.0,USA,2407368.82
2000,2001,Blood grow,Horror,2024.0,USA,521950.46

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MovieID      2001 non-null   int64
 1   Title        2001 non-null   object
 2   Genre        2001 non-null   object
 3   ReleaseYear  1998 non-null   float64
 4   Country      2001 non-null   object
 5   BudgetUSD    2001 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 93.9+ KB

In [ ]:
missing_data = dataset[dataset.isnull().any(axis=1)] #axis=1 as we find for column for raw it's 0
missing_data

    MovieID              Title   Genre  ReleaseYear Country    BudgetUSD
11       12  Score by attorney  Comedy          NaN   India    995578.82
13       14        Among money   Drama          NaN     USA   2003466.13
15       16        Similar off   Drama          NaN     USA  25624591.73

In [ ]:
dataclean1 = dataset.dropna()
dataclean1

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,China22,6577427.79
1,2,He however experience,Comedy,1988.0,USA23,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,USA24,2468079.29
3,4,Exactly live,Comedy,1998.0,USA,1447311.46
4,5,Focus improve especially?,Documentary,2021.0,India,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,Documentary,1985.0,USA,5538344.45
1997,1998,Others line four,Action,2018.0,UK,6596913.87
1998,1999,Culture theory,Drama,1986.0,France,633992.99
1999,2000,Important almost,Action,1977.0,USA,2407368.82
2000,2001,Blood grow,Horror,2024.0,USA,521950.46

In [ ]:
selected_rows = dataclean1[dataclean1['MovieID'].isin([12, 14, 16])]
selected_rows

Empty DataFrame
Columns: [MovieID, Title, Genre, ReleaseYear, Country, BudgetUSD]
Index: []

In [ ]:
noise_data = dataclean1[dataclean1['BudgetUSD']<100000]
noise_data

      MovieID            Title    Genre  ReleaseYear Country  BudgetUSD
20         21     Agree garden  Romance       2005.0     USA       10.0
32         33    From cold law   Comedy       2013.0     USA      417.0
1359     1360  Maintain record   Horror       1992.0      UK      120.0
1943     1944             Wait    Drama       2012.0     USA       33.0

In [ ]:
dataclean1.loc[dataclean1['MovieID'] == 21, 'BudgetUSD'] = 273022.95
dataclean1.loc[dataclean1['MovieID'] == 33, 'BudgetUSD']=4171378
dataclean1.loc[dataclean1['MovieID'] == 1360, 'BudgetUSD']=1203401.48
dataclean1.loc[dataclean1['MovieID'] == 1944, 'BudgetUSD']=330023.48

In [ ]:
selected_rows = dataclean1[dataclean1['MovieID'].isin([21, 33,1360, 1944])]
selected_rows

      MovieID            Title    Genre  ReleaseYear Country   BudgetUSD
20         21     Agree garden  Romance       2005.0     USA   273022.95
32         33    From cold law   Comedy       2013.0     USA  4171378.00
1359     1360  Maintain record   Horror       1992.0      UK  1203401.48
1943     1944             Wait    Drama       2012.0     USA   330023.48

In [ ]:
inconsistent_data = dataclean1[dataclean1['Country'].str.contains(r"[^a-zA-Z\s]",na=False)]
inconsistent_data

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,China22,6577427.79
1,2,He however experience,Comedy,1988.0,USA23,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,USA24,2468079.29

In [ ]:
dataclean1['Country']=dataclean1['Country'].str.replace(r"[^a-zA-Z]","",regex=True)
dataclean1

/tmp/ipython-input-2167080277.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataclean1['Country']=dataclean1['Country'].str.replace(r"[^a-zA-Z]","",regex=True)

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,China,6577427.79
1,2,He however experience,Comedy,1988.0,USA,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,USA,2468079.29
3,4,Exactly live,Comedy,1998.0,USA,1447311.46
4,5,Focus improve especially?,Documentary,2021.0,India,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,Documentary,1985.0,USA,5538344.45
1997,1998,Others line four,Action,2018.0,UK,6596913.87
1998,1999,Culture theory,Drama,1986.0,France,633992.99
1999,2000,Important almost,Action,1977.0,USA,2407368.82
2000,2001,Blood grow,Horror,2024.0,USA,521950.46

In [ ]:
# Duplicat data
duplicate_data = dataclean1[dataclean1.duplicated(keep=False)]
duplicate_data

    MovieID           Title   Genre  ReleaseYear Country    BudgetUSD
23       24  Large over the  Comedy       2014.0   India  16106357.21
29       24  Large over the  Comedy       2014.0   India  16106357.21

In [ ]:
dataclean2 = dataclean1.drop_duplicates()
dataclean2

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,China,6577427.79
1,2,He however experience,Comedy,1988.0,USA,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,USA,2468079.29
3,4,Exactly live,Comedy,1998.0,USA,1447311.46
4,5,Focus improve especially?,Documentary,2021.0,India,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,Documentary,1985.0,USA,5538344.45
1997,1998,Others line four,Action,2018.0,UK,6596913.87
1998,1999,Culture theory,Drama,1986.0,France,633992.99
1999,2000,Important almost,Action,1977.0,USA,2407368.82
2000,2001,Blood grow,Horror,2024.0,USA,521950.46

In [ ]:
select_row = dataclean2[dataclean2['MovieID'].isin([24])]
select_row

    MovieID           Title   Genre  ReleaseYear Country    BudgetUSD
23       24  Large over the  Comedy       2014.0   India  16106357.21

In [ ]:
#transform the data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataclean2['Country'] = le.fit_transform(dataclean2['Country'])
dataclean2

/tmp/ipython-input-308685106.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataclean2['Country'] = le.fit_transform(dataclean2['Country'])

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,Comedy,2003.0,2,6577427.79
1,2,He however experience,Comedy,1988.0,9,1883810.10
2,3,Star responsibility politics,Comedy,1971.0,9,2468079.29
3,4,Exactly live,Comedy,1998.0,9,1447311.46
4,5,Focus improve especially?,Documentary,2021.0,5,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,Documentary,1985.0,9,5538344.45
1997,1998,Others line four,Action,2018.0,8,6596913.87
1998,1999,Culture theory,Drama,1986.0,3,633992.99
1999,2000,Important almost,Action,1977.0,9,2407368.82
2000,2001,Blood grow,Horror,2024.0,9,521950.46

In [ ]:
dataclean2['Genre'] = le.fit_transform(dataclean2['Genre'])
for i, genre in enumerate(le.classes_):
    print(f"{i}: {genre}")
dataclean2

0: Action
1: Comedy
2: Documentary
3: Drama
4: Horror
5: Romance
6: Sci-Fi
7: Thriller

/tmp/ipython-input-1768756235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataclean2['Genre'] = le.fit_transform(dataclean2['Genre'])

,MovieID,Title,Genre,ReleaseYear,Country,BudgetUSD
0,1,Might toward capital,1,2003.0,2,6577427.79
1,2,He however experience,1,1988.0,9,1883810.10
2,3,Star responsibility politics,1,1971.0,9,2468079.29
3,4,Exactly live,1,1998.0,9,1447311.46
4,5,Focus improve especially?,2,2021.0,5,900915.86
...,...,...,...,...,...,...
1996,1997,Professional job security,2,1985.0,9,5538344.45
1997,1998,Others line four,0,2018.0,8,6596913.87
1998,1999,Culture theory,3,1986.0,3,633992.99
1999,2000,Important almost,0,1977.0,9,2407368.82
2000,2001,Blood grow,4,2024.0,9,521950.46