<a href="https://colab.research.google.com/github/JadoHR/Personal_Projects_Jean_De_Dieu/blob/main/linear_regression_multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=36d0ead3e4aba19cdf75e71b3678ba4df283f01fb05f6b04ca0ec14d8f1d6c40
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [8]:
from word2number import w2n

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
df.experience = df.experience.fillna("zero")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df['experience'] = df['experience'].fillna('zero')
df.experience = df.experience.apply(w2n.word_to_num)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [10]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [11]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [12]:
from sklearn import linear_model
# Separate features (x) and target
x = df.drop('salary($)', axis='columns')
target = df['salary($)']


# Assuming 'experience', 'test_score(out of 10)', and 'interview_score(out of 10)' are columns in your DataFrame
# Create and fit the linear regression model
reg = linear_model.LinearRegression()
reg.fit(x.values, target)

# Print coefficients and intercept
print('Coefficients:', reg.coef_)
print('Intercept:', reg.intercept_)

Coefficients: [2922.26901502 2221.30909959 2147.48256637]
Intercept: 14992.65144669314

In [13]:
print(df.columns)

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [ ]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [ ]:
reg.predict([[12,10,10]])

array([93747.79628651])

#Draft

In [14]:
import pandas as pd
from sklearn import linear_model

# Sample data
data = {'experience': [8, 8, 'five', 'two', 'seven', 'three', 'ten', 'eleven'],
        'test_score(out of 10)': [9, 6, 6, 10, 9, 7, None, 7],
        'interview_score(out of 10)': [5, 7, 10, 10, 6, 10, 7, 8],
        'salary($)': [50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000]}

df = pd.DataFrame(data)

# Convert 'experience' column to numeric, handling errors with 'coerce' to replace non-numeric values with NaN
df['experience'] = pd.to_numeric(df['experience'], errors='coerce')

# Fill missing values with a chosen strategy, e.g., median
df = df.fillna(df.median())

# Separate features (x) and target
x = df.drop('salary($)', axis='columns')
target = df['salary($)']

# Create and fit the linear regression model
reg = linear_model.LinearRegression()
reg.fit(x.values, target)

# Print coefficients and intercept
print('Coefficients:', reg.coef_)
print('Intercept:', reg.intercept_)

Coefficients: [   0.         1311.34969325 1329.75460123]
Intercept: 42529.14110429449

In [15]:
reg.predict([[12,10,10]])

array([68940.18404908])